
nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: 022f398d-cbac-4c0f-98d7-fa81e3a7088d
    data-id: application-dev.yml
    group: PARSER_GROUP
    type: yaml
    auto-refresh: true
    enable-remote-sync-config: true
    context-path: nacos
    # 此参数必须开启，若不开启则不会去调用扩展配置 bug
    bootstrap:
      log-enable: true
